config/routes.rb
SampleApp::Application.routes.draw do
  resources :users 
  resources :sessions, only: [:new, :create, :destroy] 
  root 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete' # HTTP DELETE request
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	# callback method that creates a remember_token before creating a new user in DB
	# "Method reference" - rails looks for method called create_remember_token
	before_create :create_remember_token
	
	validates(:name, presence: true, length: { maximum: 50 })
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	# VALID_EMAIL_REGEX is a constant
	# format validation
	validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: true, uniqueness: { case_sensitive: false })
	# Sometimes when user clicks submit in quick succession, duplication can still occur.
	# to avoid this, create a database index on email column.
	has_secure_password # gets all current password tests to pass
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
    SecureRandom.urlsafe_base64
  	end

  	def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  	end

  	# self allows creation of non-local variable, written to DB.
  	private
  	
  	def create_remember_token
	self.remember_token = User.encrypt(User.new_remember_token)
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # We have to explicitly include the helper modules in controllers. Not the case in case of views.
  include SessionsHelper 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new 
	end

	# inside this action, user authentication information 
	# is present
	def create
		# pulls user from the DB by email.
		user = User.find_by(email: params[:session][:email].downcase)
		  if user && user.authenticate(params[:session][:password]) #3 possible results with this logic
		    # Sign the user in and redirect to the user's show page.
		    sign_in user #sign_in function
		    redirect_back_or user # redict to requested URL if it exists or to some default URL
		  else
		    # Create an error message and re-render the signin form.
		    # flash.now is used to display flash messages on rendered pages
		    flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
		  end
	end
	
	def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # invoking signed_in_user method.
  # Filter acts only on edit and update.
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def index
    @users = User.paginate(page: params[:page]) # Key: page, value is page
    # 30 is the default number of users pulled out.
  end

  def show
  	@user = User.find(params[:id]) # params used to retrieve user id.
  end

  def new
  	@user = User.new
  end

  def create
    # params contains a hash of hashes (user attributes)
    # params[:user] is basically name: "Foo Bar", email: "foo@invalid", password: "foo", password_confirmation: "bar"
    # params[:user] passes all the submitted user data to User.new() which is unsafe
    @user = User.new(user_params)  # auxillary method user_params
    if @user.save
        sign_in @user
        flash[:success] = "Get Ready to Hate a Software!"
        redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  # Only admins can destroy as written in _user.html.erb
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters 
    def signed_in_user
      unless signed_in?
        store_location
      redirect_to signin_url, notice: "Please sign in."
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
    # create a new token
    remember_token = User.new_remember_token 

    # place unencrypted token in browser cookies
    cookies.permanent[:remember_token] = remember_token 
    
    # Save token to Database
    user.update_attribute(:remember_token, User.encrypt(remember_token))
end

def signed_in?
	!current_user.nil?
end
    
def current_user=(user)
	# set current user to user.
	# self.current_user is converted to current_user=(..)
	@current_user = user
end

 # ||= sets @current_user instance variable to the user 
 # corresponding to remember_token
def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
end

def current_user?(user)
    user == current_user
  end

def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

# Forwarding users to intended destination
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location # puts requested URL in session variable under the key :return_to
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://ihatesoftware.org/">StarpathIT</a>
    by Lalith Kumar K V N
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://starpathit.com">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "HATE A SOFTWARE", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <% if signed_in? %>
                <li><%= link_to "Users", users_path %></li>
                <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
                </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_ieshim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/ieshim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>      
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %> <!-- To avoid showing debug info to users of deployed app-->
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <!--Count returns no.of errors; Pluralize avoid gramatical "1 errors" mistakes-->
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.       
  Go back to home page here <a href="../static_pages/home">To Home Page</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Hate your software with Love</h1>

  <h2>
    Hating a software service has never been easier.
    <a href="#">Click here to Upload</a>
    sample screenshot.
  </h2>

  <%= link_to "Upload now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<!-- 
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
-->

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %> <!--form_for helper takes a block with one variable. |f| for form-->
    <!-- Rails creates form tag using @user; Rails figures that @user is of Class User; Rails knows to construct  form with POST method-->
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <!--name, email values allow Rails to construct initialization hash via params variable.
      Email attribute of user hash-->
      <%= f.label :email %>
      <%= f.text_field :email %>
      <!--Values from here get passed to User controller as symbols-->
      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>